name: 'Update Submodule Action'
on:
  repository_dispatch:
    types: update
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  update_submodules:
    name: Update submodules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          submodules: recursive
      - name: Update submodules
        run: git submodule update --init --recursive --checkout -f --remote -- "${{github.event.client_payload.module}}"

      - name: Update status
        id: status
        run: echo "::set-output name=status::$(git status -s)"

      - name: Config git
        if: ${{ steps.status.outputs.status }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          git commit -m "[BOT] Update submodules at $(date "+DATE: %Y-%m-%d TIME: %H:%M:%S")"

      - name: Push updates
        if: ${{ steps.status.outputs.status && github.event_name == 'push' }}
        run: git push
